FROM python:3.13-slim
WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./src ./src

LABEL org.opencontainers.image.authors="Stefan Kecskes"
LABEL org.opencontainers.image.vendor="skecskes"
LABEL org.opencontainers.image.source="git@github.com:skecskes/reviews-service.git"
LABEL org.opencontainers.image.licenses="MIT"

VOLUME /data_in_volume

CMD ["python", "src/ingestion/etl.py", "/data_in_volume/reviews.csv"]